version: '3'
services:
  backend:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./app/db.sqlite3:/app/db.sqlite3  # Persister la base de données SQLite
    ports:
      - "8000:8000"

  frontend:
    build: ./app
    command: npm start
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
